### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by KishibeR** [AyushSehrawat/Economy-Bot#3]
asking for 'run = "echo hello word" to be added to the file

**Comment by AyushSehrawat** [comment]
> asking for 'run = "echo hello word" to be added to the file

Looks like you are trying to use replit. If you cloned this repository using replit git functionality , they create a .replit file.
In that file you can add the run command

```
onBoot = pip3 install <dependencies >
run = python3 main.py
```
Replace < dependencies > with the modules required like
`pip3 install discord.py`

**Comment by AyushSehrawat** [comment]
> asking for 'run = "echo hello word" to be added to the file

I assumed it is .replit , if not , please elaborate more.

**Comment by KishibeR** [comment]
> > asking for 'run = "echo hello word" to be added to the file
> 
> I assumed it is .replit , if not , please elaborate more.

**Comment by KishibeR** [comment]
yes i am using replit new issue though unable to decode .replit: Near Line 1 (last key parsed 'onBoot' ): expected value but found pip instead. does that make pip the dependencies?

**Comment by AyushSehrawat** [comment]
> yes i am using replit new issue though unable to decode .replit: Near Line 1 (last key parsed 'onBoot' ): expected value but found pip instead. does that make pip the dependencies?

`.replit` files are used to run the repl which aren't created on replit, but are forked from github.. The structure of `.replit` is

![File](https://i.ibb.co/ftJZGXz/Screenshot-2021-04-09-21-50-17-631-com-android-chrome.jpg) 

This images shows the structure of replit file 

See this, 
https://pip.pypa.io/en/stable/user_guide/#requirements-files

on how to create requirements.txt file

**Comment by AyushSehrawat** [comment]
Error came, because i forgot `"` in the line
