### ISSUE TITLE
The async def shop does not work anymore

### ISSUE THREAD

**Issue by tongt-droid** [AyushSehrawat/Economy-Bot#4]

**Comment by AyushSehrawat** [comment]
Can you send the error ?

**Comment by tongt-droid** [comment]
So when I ran the bot, I typed lshop in discord, but it did not reply with anything and when I looked at my kernel, there was no error. I think the problem has something to do with for item in mainshop since discord.embed still works. Sorry for replying so late since I have class :).

**Comment by tongt-droid** [comment]
By the way, l is my prefix

**Comment by AyushSehrawat** [comment]
> 
> 
> So when I ran the bot, I typed lshop in discord, but it did not reply with anything and when I looked at my kernel, there was no error. I think the problem has something to do with for item in mainshop since discord.embed still works. Sorry for replying so late since I have class :).

Remove the try and except and send the error :)

**Comment by tongt-droid** [comment]
> > So when I ran the bot, I typed lshop in discord, but it did not reply with anything and when I looked at my kernel, there was no error. I think the problem has something to do with for item in mainshop since discord.embed still works. Sorry for replying so late since I have class :).
> 
> Remove the try and except and send the error :)

May you please elaborate more on try and except because I don't know what you mean. I am pretty new to Python so I am sorry.

**Comment by tongt-droid** [comment]
Just an update, I did it another way and it worked, but I think the reason it didn't work for me is that I may have typed the  description wrong for the for loop which is really embarrassing haha.

**Comment by AyushSehrawat** [comment]
Haha , np :)
