### ISSUE TITLE
i keep getting errors

### ISSUE THREAD

**Issue by sanzhuu** [AyushSehrawat/Economy-Bot#9]
as said in the read me file, i just copy pasted my token in the 'token' area. but i got this set of errors when i tried to run the module:(

please help, i just want an economy bot for my server 

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 606, in _load_from_module_spec
    spec.loader.exec_module(lib)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/lucky/Downloads/Economy-Bot-main/Economy_bot_code/cogs/info.py", line 3, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/lucky/Downloads/Economy-Bot-main/Economy_bot_code/main.py", line 434, in <module>
    client.load_extension(f'cogs.{filename[:-3]}')
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 678, in load_extension
    self._load_from_module_spec(spec, name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 609, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.info' raised an error: ModuleNotFoundError: No module named 'psutil'

**Comment by AyushSehrawat** [comment]
Install the module.
`https://pypi.org/project/psutil/`

**Comment by sanzhuu** [comment]
> Install the module.
> `https://pypi.org/project/psutil/`

oop alright thanks

**Comment by sanzhuu** [comment]
and also, when i added the cog folder and stuff, i got these errors

import discordfrom discord.ext import commandsimport psutil

class Info(commands.Cog):    def __init__(self, client):        self.client = client
    @commands.Cog.listener()
    async def on_ready(self):        print('Info Cog Loaded Succesfully')
    @commands.command(aliases=['python', 'botinfo'])    async def bot(self, ctx):        values = psutil.virtual_memory()        val2 = values.available * 0.001        val3 = val2 * 0.001        val4 = val3 * 0.001
        values2 = psutil.virtual_memory()        value21 = values2.total        values22 = value21 * 0.001        values23 = values22 * 0.001        values24 = values23 * 0.001
        embedve = discord.Embed(            title="Bot Info", description=None, color=0x9370DB)        embedve.add_field(            name="Bot Latency", value=f"Bot latency - {round(self.client.latency * 1000)}ms", inline=False)        embedve.add_field(name='Hosting Stats', value=f'Cpu usage- {psutil.cpu_percent(1)}%'                          f'\n(Actual Cpu Usage May Differ)'                          f'\n'
                          f'\nNumber OF Cores - {psutil.cpu_count()} '                          f'\nNumber of Physical Cores- {psutil.cpu_count(logical=False)}'                          f'\n'
                          f'\nTotal ram- {round(values24, 2)} GB'                          f'\nAvailable Ram - {round(val4, 2)} GB')
        await ctx.send(embed=embedve)
    @commands.command(aliases=['help'])    async def _help(self, ctx):        embedvar = discord.Embed(title="Help Commands",description=None, color=0x00ff00)
        embedvar.add_field(name=')bot', value='To see bot info', inline=False)        embedvar.add_field(name=')balance / )bal', value='To see your balance', inline=False)        embedvar.add_field(name=')beg', value='To beg some money', inline=False)        embedvar.add_field(name=')deposit', value='To deposit money in bank', inline=False)        embedvar.add_field(name=')withdraw', value='To withdraw money from bank', inline=False)        embedvar.add_field(name=')send', value='Send money to someone', inline=False)        embedvar.add_field(name=')rob', value='Rob some random money ', inline=False)        embedvar.add_field(name=')slots', value='To bet some money', inline=False)        embedvar.add_field(name=')shop', value='To view shop', inline=False)        embedvar.add_field(name=')buy', value='To, buy an item', inline=False)        embedvar.add_field(name=')sell', value='To sell an item', inline=False)        embedvar.add_field(name=')bag', value='To view your shopping cart', inline=False)        embedvar.add_field(name=')lb', value='To view leaderboard', inline=False)
        await ctx.send(embed=embedvar)
def setup(client):    client.add_cog(Info(client))
